### ISSUE TITLE
ファイル名に「+」が含まれるメディアのアクセスが404となる

### ISSUE THREAD

**Issue by Sinhalite** [Sinhalite/microcms-backup-tool#2]
以下の件について、別途起票した
https://github.com/Sinhalite/microcms-backup-tool/issues/1#issuecomment-2016380844

**Comment by Sinhalite** [comment]
@ryotax9814
本件の処理については、APIからのレスポンスに記載のURLに対して、そのままアクセスしているだけなので、マネジメントAPIのレスポンスに記載されているURL自体に問題がある可能性ああります。

問題の特定のため、こちらでもファイル名に「+」を入れたメディアをアップロードして、確認してみますね。

一時対処ととしては、ファイル名から「+」を取り除いていただくことで解決する可能性が高いです。

**Comment by ryotax9814** [comment]
@Sinhalite 
了解しました。お手数ですが、確認のほどお願いします。

また、microCMSの管理画面にて、ファイル名の「+」を取り除いたところ、バックアップが正常終了するようになりました。

**Comment by Sinhalite** [comment]
@ryotax9814 
ご返信できておらず、申し訳ないです🙏

ファイル名変更いただいたら、正常終了されたとのことで、承知いたしました。

こちらはAPI側の課題と思われるため、自分の方からフィードバックを出しておきます。

また、ツール側でも変換してアクセスなど、対応できることがないかは引き続き検討いたします。

**Comment by ryotax9814** [comment]
@Sinhalite 
いろいろお手数おかけします🙇
了解しました。よろしくお願いいたします。

**Comment by Sinhalite** [comment]
@ryotax9814 
こちらプロダクト側で、APIのレスポンスが修正されまして、現在は正常にアクセスできる状況かと思います。
お手数おかけしました。

**Comment by ryotax9814** [comment]
@Sinhalite 
こちらでも事象が解消されたことを確認できました。
ご対応いただき、ありがとうございました！
